### ISSUE TITLE
Capture tap event

### ISSUE THREAD

**Issue by xesjkeee** [lepikhinb/tinymotion#1]
Hey, Boris 👋
Thanks for your library!

I have an issue with click event, so I use macbook's touchpad for surfing and my touchpad on tap event triggers like click event

So your demo https://tinymotion.me/#click not visualize it

I think you could add `touchstart` and `touchend` listeners for here https://github.com/lepikhinb/tinymotion/blob/master/src/animator.js#L40

**Comment by lepikhinb** [comment]
Hi,

I'm going to implement it soon. Meanwhile you're welcome to make a PR 😄

**Comment by shannonrothe** [comment]
@lepikhinb fixed in #3 👍🏼
